"Spacing":
  - "src/spacing/*"

"Flexbox":
  - "src/flexbox/*"

"Border":
  - "src/border/*"

"Typography":
  - "src/typography/*"

"Layout":
  - "src/layout/*"

"Effects":
  - "src/effects/*"

"Sizing":
  - "src/sizing/*"

"CI":
  - ".github/**/*"
